NAME	=	philo_bonus
FLAG	=	-Wall -Wextra -Werror -pthread -fsanitize=thread -g

SRC	=	./src/checker/checker.c \
		./src/checker/check_int.c \
		./src/get_time/get_time.c \
		./src/libft/ft_atoi.c \
		./src/main/main.c \
		./src/main/life.c \
		./src/main/sets.c \
		./src/main/check_die.c \
		./src/main/sets2.c \
		./src/main/free.c


all: $(NAME)

$(NAME):
	@gcc $(FLAG) $(SRC) -o $(NAME)
	@rm -rf philo_bonus.dSYM
	@printf "\n\033[92m   Downloading... \033[0m\n  "
	@printf "\033[92m █"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "\033[0m\n\n"
	@echo "   GitHub    ~>  \033[4;1;34menverbey\033[0m"
	@echo "   42 Intra  ~>  \033[4;1;34menvyilma\033[0m \n"
clean:
	@rm -rf $(OBJ)
	@printf "\n\033[91m   Deleting... \033[0m\n  "
	@printf "\033[91m █"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "█"
	@sleep 0.01
	@printf "\033[0m\n\n"
	@rm -rf philo_bonus.dSYM
#@echo "\n \033[91m   ->files deleted by AVCI<-\033[91m\n "

line:
	@printf "ᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓᚓ\n"

fclean: clean
	@rm -rf $(NAME)

char = 127

re: fclean line all

.PHONY: all clean fclean re